version: "3.1" 
services:
  huydv-memcached:
    image: "memcached:latest"
    container_name: huydv-memcached
    restart: always
    hostname: memcached
    networks:
      - my-network
    command:
      - "--conn-limit=2048"
      - "--memory-limit=2048"
  huydv-apache:
    image: "httpd"
    container_name: huydv-httpd
    restart: always
    hostname: httpd
    networks:
      - my-network
    ports:
      - "8888:80"
      - "443:443"
    volumes:
      - ./Docker:/home/Docker
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
  huydv-mysql:
    image: "mysql"
    container_name: huydv-mysql
    restart: always
    hostname: mysql
    networks:
      - my-network
    environment:
      MYSQL_ROOT_PASSWORD: a123456
      MYSQL_DATABASE: huydv
      MYSQL_USER: huydv
      MYSQL_PASSWORD: a123456
    volumes:
      - ./db:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
  huydv-php:
    container_name: huydv-php
    build:
      dockerfile: Dockerfile
      context: ./
    hostname: php
    restart: always
    networks:
      - my-network
    volumes:
      - ./Docker:/home/Docker

#network
networks:
  my-network:
    driver: bridge

#disk
volumes:
  dir-site:
    driver_opts:
      device: /Docker/
      o: bind
      type: tmpfs